# =============================================================================
# src/models/stage2_classifier.py — Stage 2: Supervised Classification
# =============================================================================
# Stage 2 takes the pseudo-labels generated by Stage 1 (Isolation Forest)
# and trains two supervised classifiers:
#   1. XGBoost  — gradient boosting (typically best performer)
#   2. Random Forest — ensemble of decision trees (for comparison)
#
# SMOTE is applied to the training data to correct class imbalance before
# fitting either model.
#
# Outputs:
#   outputs/models/stage2_xgboost.pkl
#   outputs/models/stage2_random_forest.pkl
#   outputs/results/stage2_results.csv
#   outputs/results/stage2_metrics.json
#   outputs/figures/stage2_confusion_matrix_xgb.png
#   outputs/figures/stage2_confusion_matrix_rf.png
#   outputs/figures/stage2_feature_importance.png
#
# Run: python src/models/stage2_classifier.py
# =============================================================================

import os
import sys
import json
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    f1_score, precision_score, recall_score,
    roc_auc_score, matthews_corrcoef,
    classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.model_selection import StratifiedKFold
from imblearn.over_sampling import SMOTE

try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False
    print("WARNING: XGBoost not installed. Only Random Forest will run.")

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import config
from src.utils.helpers import setup_logger, ensure_directories, check_file_exists

logger = setup_logger(__name__)


# =============================================================================
# Load Data
# =============================================================================

def load_data() -> tuple:
    """
    Loads train and test splits.

    For Stage 2, we use:
    - Training: the pseudo-labeled training data from Stage 1
      (train_with_pseudo_labels.csv) OR the original train.csv
    - Test: the held-out test set (never used in training)

    We use pseudo_label (from Stage 1) as the training signal,
    and true label for final evaluation.
    """
    logger.info("Loading data for Stage 2...")

    pseudo_path = os.path.join(config.PROCESSED_DIR, "train_with_pseudo_labels.csv")

    if os.path.exists(pseudo_path):
        train = pd.read_csv(pseudo_path)
        # Use pseudo_label for training if available, else fall back to label
        train_label_col = "pseudo_label" if "pseudo_label" in train.columns else "label"
        logger.info(f"Using pseudo-labels from Stage 1 (column: {train_label_col})")
    else:
        logger.warning("Pseudo-labels not found, using original labels")
        train = pd.read_csv(config.TRAIN_FILE)
        train_label_col = "label"

    test = pd.read_csv(config.TEST_FILE)

    X_train = train[config.FEATURE_COLUMNS]
    y_train = train[train_label_col]

    X_test = test[config.FEATURE_COLUMNS]
    y_test = test[config.TARGET_COLUMN]

    logger.info(f"Training: {X_train.shape[0]:,} rows x {X_train.shape[1]} features")
    logger.info(f"Training labels: {y_train.sum():,} non-compliant / {len(y_train):,} total ({y_train.mean()*100:.1f}%)")
    logger.info(f"Test: {X_test.shape[0]:,} rows")
    logger.info(f"Test labels: {y_test.sum():,} non-compliant / {len(y_test):,} total")

    return X_train, y_train, X_test, y_test


# =============================================================================
# Apply SMOTE
# =============================================================================

def apply_smote(X_train: pd.DataFrame, y_train: pd.Series) -> tuple:
    """
    Applies SMOTE to correct class imbalance in the training data.

    SMOTE creates synthetic minority-class samples by interpolating between
    existing non-compliant records in feature space. This is applied ONLY
    to training data — the test set is never resampled.

    Args:
        X_train: Training features
        y_train: Training labels (may be pseudo-labels from Stage 1)

    Returns:
        Tuple of (X_resampled, y_resampled) with balanced class distribution
    """
    logger.info("Applying SMOTE to training data...")
    logger.info(f"Before SMOTE: {y_train.sum():,} non-compliant / {len(y_train):,} total")

    smote = SMOTE(**config.SMOTE_CONFIG)
    X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

    n_compliant = (y_resampled == 0).sum()
    n_non_compliant = (y_resampled == 1).sum()
    logger.info(f"After SMOTE:  {n_non_compliant:,} non-compliant / {len(y_resampled):,} total")
    logger.info(f"  Compliant (0):     {n_compliant:,} ({n_compliant/len(y_resampled)*100:.1f}%)")
    logger.info(f"  Non-compliant (1): {n_non_compliant:,} ({n_non_compliant/len(y_resampled)*100:.1f}%)")

    return X_resampled, y_resampled


# =============================================================================
# Train Models
# =============================================================================

def train_xgboost(X_train: np.ndarray, y_train: np.ndarray) -> object:
    """
    Trains an XGBoost gradient boosting classifier.

    XGBoost is the primary Stage 2 model. It typically outperforms Random
    Forest on tabular data with imbalanced classes.

    Key hyperparameters (from config.py):
        scale_pos_weight: Adjusts for remaining imbalance after SMOTE
        early_stopping_rounds: Stops if validation score doesn't improve
    """
    if not XGBOOST_AVAILABLE:
        return None

    logger.info("Training XGBoost classifier...")

    cfg = config.XGBOOST_CONFIG.copy()
    # Remove early_stopping_rounds since we have no eval set
    cfg.pop("early_stopping_rounds", None)
    cfg.pop("eval_metric", None)

    model = xgb.XGBClassifier(
        **cfg,
        use_label_encoder=False,
        verbosity=0,
    )
    model.fit(X_train, y_train)

    logger.info("XGBoost training complete.")
    return model


def train_random_forest(X_train: np.ndarray, y_train: np.ndarray) -> RandomForestClassifier:
    """
    Trains a Random Forest classifier.

    Random Forest serves as the comparison baseline to XGBoost.
    It is also used to compute feature importance scores for Table VII.
    """
    logger.info("Training Random Forest classifier...")

    model = RandomForestClassifier(**config.RANDOM_FOREST_CONFIG)
    model.fit(X_train, y_train)

    logger.info("Random Forest training complete.")
    return model


# =============================================================================
# Cross-Validation
# =============================================================================

def cross_validate_model(model_class, model_kwargs: dict,
                          X: np.ndarray, y: np.ndarray,
                          model_name: str) -> dict:
    """
    Runs 5-fold stratified cross-validation on the training data.

    Cross-validation gives us a more reliable estimate of model performance
    than a single train/test split. We report mean +/- std across folds.

    Args:
        model_class:   The model class to instantiate (e.g., XGBClassifier)
        model_kwargs:  Keyword arguments to pass to the model constructor
        X:             Feature matrix
        y:             Labels
        model_name:    Name for logging

    Returns:
        Dictionary of metric_name -> (mean, std) tuples
    """
    logger.info(f"Running {config.CV_FOLDS}-fold cross-validation for {model_name}...")

    skf = StratifiedKFold(n_splits=config.CV_FOLDS, shuffle=True, random_state=42)

    fold_metrics = {"f1": [], "recall": [], "precision": [], "mcc": []}

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        X_fold_train, X_fold_val = X[train_idx], X[val_idx]
        y_fold_train, y_fold_val = y[train_idx], y[val_idx]

        # Apply SMOTE on each fold's training data separately
        smote = SMOTE(**config.SMOTE_CONFIG)
        X_fold_train_sm, y_fold_train_sm = smote.fit_resample(X_fold_train, y_fold_train)

        model = model_class(**model_kwargs)
        model.fit(X_fold_train_sm, y_fold_train_sm)
        preds = model.predict(X_fold_val)

        fold_metrics["f1"].append(f1_score(y_fold_val, preds, pos_label=1, zero_division=0))
        fold_metrics["recall"].append(recall_score(y_fold_val, preds, pos_label=1, zero_division=0))
        fold_metrics["precision"].append(precision_score(y_fold_val, preds, pos_label=1, zero_division=0))
        fold_metrics["mcc"].append(matthews_corrcoef(y_fold_val, preds))

        logger.info(f"  Fold {fold+1}: F1={fold_metrics['f1'][-1]:.4f}")

    cv_results = {
        metric: {"mean": float(np.mean(vals)), "std": float(np.std(vals))}
        for metric, vals in fold_metrics.items()
    }

    logger.info(f"{model_name} CV Results:")
    for metric, stats in cv_results.items():
        logger.info(f"  {metric}: {stats['mean']:.4f} +/- {stats['std']:.4f}")

    return cv_results


# =============================================================================
# Evaluate on Test Set
# =============================================================================

def evaluate_model(model, X_test: pd.DataFrame, y_test: pd.Series,
                   model_name: str) -> dict:
    """
    Evaluates a trained model on the held-out test set.

    This is the final evaluation — these numbers go into the paper's
    results tables. The test set is only used here, never during training.

    Args:
        model:       Trained model with predict() and predict_proba() methods
        X_test:      Test features
        y_test:      True test labels
        model_name:  Name for logging and output files

    Returns:
        Dictionary of metric scores
    """
    logger.info(f"Evaluating {model_name} on test set...")

    predictions = model.predict(X_test)
    probabilities = model.predict_proba(X_test)[:, 1]

    f1        = f1_score(y_test, predictions, pos_label=1, zero_division=0)
    recall    = recall_score(y_test, predictions, pos_label=1, zero_division=0)
    precision = precision_score(y_test, predictions, pos_label=1, zero_division=0)
    mcc       = matthews_corrcoef(y_test, predictions)
    roc_auc   = roc_auc_score(y_test, probabilities)

    metrics = {
        "model":     model_name,
        "f1":        round(f1, 4),
        "recall":    round(recall, 4),
        "precision": round(precision, 4),
        "mcc":       round(mcc, 4),
        "roc_auc":   round(roc_auc, 4),
    }

    logger.info(f"\n{'='*50}")
    logger.info(f"  {model_name} — Test Set Results")
    logger.info(f"{'='*50}")
    logger.info(f"  F1 Score:  {f1:.4f}  <- primary metric")
    logger.info(f"  Recall:    {recall:.4f}")
    logger.info(f"  Precision: {precision:.4f}")
    logger.info(f"  MCC:       {mcc:.4f}")
    logger.info(f"  ROC-AUC:   {roc_auc:.4f}")
    logger.info(f"{'='*50}")
    logger.info("\nDetailed Classification Report:")
    logger.info("\n" + classification_report(
        y_test, predictions,
        target_names=["Compliant (0)", "Non-Compliant (1)"],
        zero_division=0
    ))

    return metrics, predictions, probabilities


# =============================================================================
# Feature Importance
# =============================================================================

def compute_feature_importance(rf_model: RandomForestClassifier) -> pd.DataFrame:
    """
    Computes feature importance scores from the Random Forest model.

    We use Mean Decrease in Impurity (MDI) — the default for scikit-learn
    Random Forests. This matches the paper's Table VII methodology.

    Args:
        rf_model: Trained RandomForestClassifier

    Returns:
        DataFrame with feature names and importance scores, sorted descending
    """
    logger.info("Computing feature importance scores...")

    importances = rf_model.feature_importances_
    std = np.std([tree.feature_importances_ for tree in rf_model.estimators_], axis=0)

    importance_df = pd.DataFrame({
        "feature":    config.FEATURE_COLUMNS,
        "importance": importances,
        "std":        std,
    }).sort_values("importance", ascending=False).reset_index(drop=True)

    logger.info("Feature Importance (Table VII):")
    for _, row in importance_df.iterrows():
        logger.info(f"  {row['feature']:<25} {row['importance']:.4f} +/- {row['std']:.4f}")

    return importance_df


# =============================================================================
# Save Outputs
# =============================================================================

def save_outputs(xgb_model, rf_model, X_test: pd.DataFrame,
                 y_test: pd.Series, all_metrics: list,
                 importance_df: pd.DataFrame) -> None:
    """
    Saves all Stage 2 outputs: models, metrics, confusion matrices, and
    the feature importance plot for the paper.
    """
    # Save models
    if xgb_model is not None:
        with open(os.path.join(config.MODELS_DIR, "stage2_xgboost.pkl"), "wb") as f:
            pickle.dump(xgb_model, f)
        logger.info("Saved XGBoost model")

    with open(os.path.join(config.MODELS_DIR, "stage2_random_forest.pkl"), "wb") as f:
        pickle.dump(rf_model, f)
    logger.info("Saved Random Forest model")

    # Save metrics JSON
    metrics_path = os.path.join(config.RESULTS_DIR, "stage2_metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(all_metrics, f, indent=2)
    logger.info(f"Saved metrics: {metrics_path}")

    # Save feature importance CSV
    importance_path = os.path.join(config.RESULTS_DIR, "stage2_feature_importance.csv")
    importance_df.to_csv(importance_path, index=False)
    logger.info(f"Saved feature importance: {importance_path}")

    # Save confusion matrices
    for model, name, suffix in [
        (xgb_model, "XGBoost", "xgb"),
        (rf_model, "Random Forest", "rf")
    ]:
        if model is None:
            continue
        preds = model.predict(X_test)
        cm = confusion_matrix(y_test, preds)
        fig, ax = plt.subplots(figsize=(6, 5))
        disp = ConfusionMatrixDisplay(
            confusion_matrix=cm,
            display_labels=["Compliant", "Non-Compliant"]
        )
        disp.plot(ax=ax, cmap="Blues", colorbar=False)
        ax.set_title(f"Stage 2: {name}\nConfusion Matrix (Test Set)")
        plt.tight_layout()
        cm_path = os.path.join(config.FIGURES_DIR, f"stage2_confusion_matrix_{suffix}.png")
        plt.savefig(cm_path, dpi=150, bbox_inches="tight")
        plt.close()
        logger.info(f"Saved confusion matrix: {cm_path}")

    # Save feature importance plot
    fig, ax = plt.subplots(figsize=(8, 5))
    bars = ax.barh(
        importance_df["feature"][::-1],
        importance_df["importance"][::-1],
        xerr=importance_df["std"][::-1],
        color="#2196F3", alpha=0.8, capsize=4
    )
    ax.set_xlabel("Mean Decrease in Impurity (MDI)")
    ax.set_title("CloudGuard Feature Importance (Random Forest MDI)\nTable VII — IEEE HiPC 2026")
    ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()
    fi_path = os.path.join(config.FIGURES_DIR, "stage2_feature_importance.png")
    plt.savefig(fi_path, dpi=150, bbox_inches="tight")
    plt.close()
    logger.info(f"Saved feature importance plot: {fi_path}")


# =============================================================================
# Public entry point
# =============================================================================

def run_stage2() -> dict:
    """Called by run_pipeline.py"""
    ensure_directories()

    X_train, y_train, X_test, y_test = load_data()

    # Apply SMOTE to training data
    X_train_sm, y_train_sm = apply_smote(X_train, y_train)
    X_train_arr = X_train_sm.values if hasattr(X_train_sm, 'values') else X_train_sm
    y_train_arr = y_train_sm.values if hasattr(y_train_sm, 'values') else y_train_sm

    all_metrics = []

    # Train XGBoost
    xgb_model = None
    if XGBOOST_AVAILABLE:
        xgb_cfg = {k: v for k, v in config.XGBOOST_CONFIG.items()
                   if k not in ("early_stopping_rounds", "eval_metric")}
        xgb_model = train_xgboost(X_train_arr, y_train_arr)
        xgb_metrics, _, _ = evaluate_model(xgb_model, X_test, y_test, "XGBoost")
        all_metrics.append(xgb_metrics)

    # Train Random Forest
    rf_model = train_random_forest(X_train_arr, y_train_arr)
    rf_metrics, _, _ = evaluate_model(rf_model, X_test, y_test, "Random Forest")
    all_metrics.append(rf_metrics)

    # Feature importance from Random Forest
    importance_df = compute_feature_importance(rf_model)

    # Save everything
    save_outputs(xgb_model, rf_model, X_test, y_test, all_metrics, importance_df)

    return all_metrics


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    logger.info("CloudGuard - Stage 2: Supervised Classification")
    logger.info("Models: XGBoost + Random Forest with SMOTE")
    metrics = run_stage2()

    logger.info("\n" + "=" * 60)
    logger.info("Stage 2 complete!")
    logger.info("Results saved to: " + config.RESULTS_DIR)
    logger.info("Next step: Upload notebooks/stage3_cnn_lstm.ipynb to Google Colab")
    logger.info("=" * 60)
